repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'cd /Users/joshuaklein/code/fail-ci-build-on-ff/ci-fail && PYTHONPATH=app python -m pytest tests/ -v'
        language: system
        types: [python]
        pass_filenames: false
        always_run: true

      - id: python-check-syntax
        name: python syntax check
        entry: python -m py_compile
        language: system
        types: [python]