pipeline:
  identifier: Build_fme_tech_debt_validator_1757679598104
  name: Build fme-tech-debt-validator
  orgIdentifier: SplitTrainingFME
  projectIdentifier: Workshop
  properties:
    ci:
      codebase:
        build: <+input>
        repoName: fme-tech-debt-validator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    shell: Sh
                    command: |-
                      pip install flake8
                      flake8 . --max-line-length=88 --extend-ignore=E203,W503
                        --exclude=.venv
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    repo: fme-tech-debt-validator
                    tags:
                      - latest
                    caching: true
                    registryRef: ci-build
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
