pipeline:
  identifier: Build_fme_tech_debt_validator_1757679598104
  name: Build fme-tech-debt-validator
  orgIdentifier: SplitTrainingFME
  projectIdentifier: Workshop
  properties:
    ci:
      codebase:
        build: <+input>
        repoName: fme-tech-debt-validator
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: runlinter
                  name: run linter
                  spec:
                    shell: Sh
                    command: |-
                      pip install flake8
                      flake8 . --max-line-length=150 --extend-ignore=W293,W291,E203
                  timeout: ""
                  type: Run
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    shell: Sh
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -r requirements-test.txt
                  timeout: ""
                  type: Run
              - step:
                  identifier: runtests
                  name: run tests
                  spec:
                    shell: Sh
                    command: |-
                      . .venv/bin/activate
                      export PYTHONPATH=app
                      python -m pytest tests/ -v --cov=app --cov-report=term
                      echo "✅ All tests passed!"
                  timeout: 10m
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    repo: fme-tech-debt-validator
                    tags:
                      - latest
                    caching: true
                    registryRef: ci-build
                  timeout: ""
                  type: BuildAndPushDockerRegistry
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - stage:
        name: build sample code
        identifier: build_sample_code
        description: ""
        type: Pipeline
        spec:
          org: SplitTrainingFME
          pipeline: Build_sample_code_to_validate_1757685619630
          project: Workshop
          inputSetReferences:
            - Build_sample_code_to_validate_1757685619630prtriggerinputset
        when:
          pipelineStatus: Success
